#!/bin/bash
# Generated by SkemaDok seed-bulk — Docker exec variant
# The target database must be offline before running this script.
set -euo pipefail

DATABASE=${database}
CONTAINER=neo4j        # name or ID of your running Neo4j container
IMPORT_DIR=/import     # path INSIDE the container where the import files are mounted

docker exec -u neo4j "$CONTAINER" \
  neo4j-admin database import full "$DATABASE" \
    --overwrite-destination=true \
    --input-type=parquet \
    --path-pattern-style=glob \
    --format=block \
    --nodes="$IMPORT_DIR/nodes/*.parquet" \
    --relationships="$IMPORT_DIR/relationships/*.parquet"
