#!/bin/bash
# Generated by SkemaDok seed-bulk
# The target database must be offline before running this script.
set -euo pipefail

DATABASE=${database}
IMPORT_DIR=${importDir}

neo4j-admin database import full "$DATABASE" \
  --overwrite-destination=true \
  --input-type=parquet \
  --path-pattern-style=glob \
  --format=block \
  --nodes="$IMPORT_DIR/nodes/*.parquet" \
  --relationships="$IMPORT_DIR/relationships/*.parquet"
