package com.neo4j.skemadok.bulk;

import com.neo4j.skemadok.model.SchemaDocument;
import com.neo4j.skemadok.seeder.ConstraintDdl;
import com.neo4j.skemadok.seeder.IndexDdl;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Writes a {@code schema.cypher} file containing the {@code CREATE CONSTRAINT} and
 * {@code CREATE INDEX} statements needed to reproduce the source database's schema after a
 * {@code neo4j-admin database import full} run.
 *
 * <p>Constraints are written before indexes because some indexes are implied by constraints
 * (e.g. the backing index of a UNIQUENESS constraint). Both sets use {@code IF NOT EXISTS}
 * so the file is safe to re-run. The file ends with {@code CALL db.awaitIndexes(300)} to
 * block until all index populations finish before the caller proceeds.
 */
class SchemaCypherWriter {

    private final SchemaDocument schema;

    SchemaCypherWriter(SchemaDocument schema) {
        this.schema = schema;
    }

    Path write(Path outputDir) throws IOException {
        var outputPath = outputDir.resolve("schema.cypher");
        var nl = "\n";
        var sb = new StringBuilder();

        sb.append("// Schema DDL generated by SkemaDok seed-bulk").append(nl);
        sb.append("// Run after neo4j-admin import to restore constraints and indexes:").append(nl);
        sb.append("//   cat schema.cypher | cypher-shell -u neo4j -p <password> -d <database>").append(nl);
        sb.append(nl);

        sb.append("// Constraints").append(nl);
        int constraintCount = 0;
        if (schema.getConstraints() != null) {
            for (var constraint : schema.getConstraints()) {
                var ddl = ConstraintDdl.build(constraint);
                if (ddl != null) {
                    sb.append(ddl).append(";").append(nl);
                    constraintCount++;
                }
            }
        }
        if (constraintCount == 0) {
            sb.append("// (none)").append(nl);
        }

        sb.append(nl);
        sb.append("// Indexes").append(nl);
        int indexCount = 0;
        if (schema.getIndexes() != null) {
            for (var index : schema.getIndexes()) {
                var ddl = IndexDdl.build(index);
                if (ddl != null) {
                    sb.append(ddl).append(";").append(nl);
                    indexCount++;
                }
            }
        }
        if (indexCount == 0) {
            sb.append("// (none)").append(nl);
        }

        sb.append(nl);
        sb.append("// Wait for all index populations to complete (timeout 300 s)").append(nl);
        sb.append("CALL db.awaitIndexes(300);").append(nl);

        Files.writeString(outputPath, sb.toString());
        return outputPath;
    }
}
